[general]
import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
padding = { x = 15, y = 15 }
opacity = 0.975

[scrolling]
history = 5000

[cursor]
style = { blinking = "Always" }
thickness = 0.2

[terminal]
shell = "fish"

[mouse]
hide_when_typing = true

[font]
normal = { family = "GeistMono Nerd Font" }
size = 10

